 "use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { LayoutDashboard,Users,CheckSquare,Activity,ChartNoAxesCombined,LogOut,Plus,Search,ArrowUpRight,Download } from "lucide-react";
type Client={id:string;name:string;company:string|null;email:string|null;status:string;created_at:string};
type Task={id:string;title:string;due_date:string|null;status:string;created_at:string};
type ActivityRow={id:string;title:string;kind:string;created_at:string};
const sections=[["overview","Panel",LayoutDashboard],["clients","Clientes",Users],["tasks","Tareas",CheckSquare],["activities","Actividad",Activity],["reports","Informes",ChartNoAxesCombined]] as const;
export default function Dashboard(){
 const router=useRouter();const [section,setSection]=useState<string>("overview");const [user,setUser]=useState("");const [clients,setClients]=useState<Client[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [events,setEvents]=useState<ActivityRow[]>([]);const [query,setQuery]=useState("");const [modal,setModal]=useState(false);const [name,setName]=useState("");const [company,setCompany]=useState("");const [email,setEmail]=useState("");const [taskTitle,setTaskTitle]=useState("");const [message,setMessage]=useState("");
 const configured=!!supabase;
 async function load(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return}setUser(user.email||"");const [c,t,a]=await Promise.all([supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("tasks").select("*").order("created_at",{ascending:false}),supabase.from("activities").select("*").order("created_at",{ascending:false}).limit(8)]);if(c.data)setClients(c.data as Client[]);if(t.data)setTasks(t.data as Task[]);if(a.data)setEvents(a.data as ActivityRow[]);}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>clients.filter(c=>[c.name,c.company||"",c.email||""].join(" ").toLowerCase().includes(query.toLowerCase())),[clients,query]);
 async function addClient(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from("clients").insert({user_id:user.id,name,company:company||null,email:email||null,status:"Lead"});if(error){setMessage(error.message);return}setName("");setCompany("");setEmail("");setModal(false);setMessage("Cliente añadido.");load();}
 async function addTask(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from("tasks").insert({user_id:user.id,title:taskTitle,status:"Pendiente"});if(error){setMessage(error.message);return}setTaskTitle("");setModal(false);setMessage("Tarea creada.");load();}
 async function signout(){await supabase?.auth.signOut();router.push("/login")}
 function exportCsv(){const rows=[["Empresa","Contacto","Correo","Estado"],...clients.map(c=>[c.company||"",c.name,c.email||"",c.status])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"}));a.download="pur-one-clientes.csv";a.click();URL.revokeObjectURL(a.href);}
 const title=sections.find(s=>s[0]===section)?.[1]||"Panel";
 return <div className="shell"><aside className="sidebar"><div className="brand">PUR <span>ONE</span></div><nav className="nav">{sections.map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMessage("")}}><Icon size={18}/>{label}</button>)}</nav><div className="side-note"><b>Espacio de trabajo</b><br/>Tu operación, organizada.<br/><span style={{color:"var(--green)"}}>Plan inicial · PUR ONE</span></div><button className="nav" onClick={signout} style={{border:0,background:"transparent",textAlign:"left",padding:12,color:"var(--muted)",display:"flex",gap:10}}><LogOut size={17}/> Cerrar sesión</button></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">PUR ONE / Workspace</div><h1 className="heading">{title==="Panel"?"Buenos días":title}</h1><p className="sub">{title==="Panel"?"Aquí tienes el resumen de tu actividad.":"Administra tu espacio de trabajo desde aquí."}</p></div><div className="avatar" title={user}>{user?user.slice(0,1).toUpperCase():"P"}</div></header>
 {!configured&&<div className="notice">La aplicación necesita las variables de Supabase para habilitar el acceso y guardar datos.</div>}{message&&<div className="notice" style={{background:"#eaf4ef",color:"var(--green)",borderColor:"#cde3d7"}}>{message}</div>}
 {section==="overview"&&<><div className="cards">{[[Users,"Clientes",clients.length,"En tu cartera"],[CheckSquare,"Tareas abiertas",tasks.filter(t=>t.status!=="Completada").length,"Pendientes de completar"],[Activity,"Actividades",events.length,"Registros recientes"],[ChartNoAxesCombined,"Tareas completadas",tasks.filter(t=>t.status==="Completada").length,"Finalizadas"]].map(([Icon,label,value,foot]:any)=><div className="card" key={label}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className="metric-label">{label}</span><Icon size={19} color="var(--green)"/></div><div className="metric">{value}</div><div className="metric-foot">{foot}</div></div>)}</div><div className="two-col"><section className="panel"><h2 className="section-title">Clientes recientes</h2>{clients.slice(0,5).length?clients.slice(0,5).map(c=><div className="row-item" key={c.id}><div><b>{c.name}</b><div className="sub" style={{marginTop:4}}>{c.company||c.email||"Sin detalles"}</div></div><span className="pill">{c.status}</span></div>):<div className="empty">Todavía no hay clientes.<br/>Añade el primero para empezar.</div>}<button className="btn secondary" style={{marginTop:12}} onClick={()=>setSection("clients")}>Ver clientes <ArrowUpRight size={15} style={{verticalAlign:"middle"}}/></button></section><section className="panel"><h2 className="section-title">Tareas pendientes</h2>{tasks.filter(t=>t.status!=="Completada").slice(0,5).length?tasks.filter(t=>t.status!=="Completada").slice(0,5).map(t=><div className="row-item" key={t.id}><b>{t.title}</b><span className="pill">Pendiente</span></div>):<div className="empty">No hay tareas pendientes.</div>}<button className="btn secondary" style={{marginTop:12}} onClick={()=>{setSection("tasks");setModal(true)}}><Plus size={15} style={{verticalAlign:"middle"}}/> Nueva tarea</button></section></div></>}
 {section==="clients"&&<><div className="page-actions"><input className="search" placeholder="Buscar clientes…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="actions"><button className="btn secondary" onClick={exportCsv}><Download size={16} style={{verticalAlign:"middle"}}/> Exportar CSV</button><button className="btn" onClick={()=>setModal(true)}><Plus size={16} style={{verticalAlign:"middle"}}/> Añadir cliente</button></div></div><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Empresa</th><th>Correo</th><th>Estado</th><th>Alta</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.company||"—"}</td><td>{c.email||"—"}</td><td><span className="pill">{c.status}</span></td><td>{new Date(c.created_at).toLocaleDateString("es-ES")}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No se encontraron clientes.</div>}</div></>}
 {section==="tasks"&&<><div className="page-actions"><p className="sub">Organiza tus próximos pasos y mantén el trabajo en movimiento.</p><button className="btn" onClick={()=>setModal(true)}><Plus size={16} style={{verticalAlign:"middle"}}/> Nueva tarea</button></div><div className="panel">{tasks.length?tasks.map(t=><div className="row-item" key={t.id}><div><b>{t.title}</b><div className="sub" style={{marginTop:4}}>{t.due_date?new Date(t.due_date).toLocaleDateString("es-ES"):"Sin fecha límite"}</div></div><button className="pill" onClick={async()=>{await supabase?.from("tasks").update({status:t.status==="Completada"?"Pendiente":"Completada"}).eq("id",t.id);load()}}>{t.status==="Completada"?"Completada · Reabrir":"Marcar completada"}</button></div>):<div className="empty">Aún no hay tareas registradas.</div>}</div></>}
 {section==="activities"&&<div className="panel"><h2 className="section-title">Actividad reciente</h2>{events.length?events.map(a=><div className="row-item" key={a.id}><div><b>{a.title}</b><div className="sub" style={{marginTop:4}}>{a.kind}</div></div><span className="sub">{new Date(a.created_at).toLocaleDateString("es-ES")}</span></div>):<div className="empty">Las actividades aparecerán aquí cuando se registren.</div>}<p className="sub" style={{fontSize:12}}>El registro manual de actividad se habilitará en una siguiente iteración.</p></div>}
 {section==="reports"&&<><div className="cards"><div className="card"><div className="metric-label">Total clientes</div><div className="metric">{clients.length}</div></div><div className="card"><div className="metric-label">Leads</div><div className="metric">{clients.filter(c=>c.status==="Lead").length}</div></div><div className="card"><div className="metric-label">Tareas pendientes</div><div className="metric">{tasks.filter(t=>t.status!=="Completada").length}</div></div><div className="card"><div className="metric-label">Completadas</div><div className="metric">{tasks.filter(t=>t.status==="Completada").length}</div></div></div><section className="panel"><h2 className="section-title">Exportación de datos</h2><p className="sub">Descarga el listado de clientes para trabajarlo en Excel o compartirlo.</p><button className="btn" onClick={exportCsv}><Download size={16} style={{verticalAlign:"middle"}}/> Exportar clientes CSV</button></section></>}
 </main>{modal&&<div style={{position:"fixed",inset:0,background:"#10231c88",display:"grid",placeItems:"center",padding:18,zIndex:10}}><section className="auth-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 className="section-title">{section==="tasks"?"Crear tarea":"Añadir cliente"}</h2><button className="btn secondary" onClick={()=>{setModal(false);setMessage("")}}>Cerrar</button></div>{section==="tasks"?<form onSubmit={addTask}><div className="field"><label>Nombre de la tarea</label><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} required placeholder="Ej. Preparar propuesta"/></div><button className="btn">Guardar tarea</button></form>:<form onSubmit={addClient}><div className="field"><label>Nombre de contacto</label><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Nombre y apellidos"/></div><div className="field"><label>Empresa</label><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nombre de empresa"/></div><div className="field"><label>Correo electrónico</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="contacto@empresa.com"/></div><button className="btn">Guardar cliente</button></form>}</section></div>}</div>;
}